name: app_estacion_meteorologica
description: App Android para mostrar datos de la estación meteorológica (scaffolding).
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  flutter_dotenv: ^5.0.2
  sqflite: ^2.0.0+4
  path: ^1.8.2
  path_provider: ^2.0.14
  fl_chart: ^1.1.1
  pdf: ^3.10.1
  printing: ^5.9.0
  intl: ^0.18.0
  home_widget: ^0.7.0
  google_fonts: ^6.2.1
  weather_icons: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
